import { loadStripe } from "@stripe/stripe-js";
export const stripePromise = loadStripe(
  import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
);
export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    hours: 10,
    monthlyPrice: 19,
    oneTimePrice: 23,
    monthlyPriceId: "price_1UCbAoIB3x0oivZ1InO6fdO9",
    oneTimePriceId: "price_1UCbGGIB3x0oivZ1mzde9Rhg",
    description: "Perfect for getting started",
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "10 hours of processing",
      "AI picks your 2–3 best clips",
      "Every major platform supported",
      "Blur, crop, or custom background",
      "Download ready to post",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    hours: 25,
    monthlyPrice: 39,
    oneTimePrice: 45,
    monthlyPriceId: "price_1UCbBQIB3x0oivZ1OgoGflki",
    oneTimePriceId: "price_1UCbHKIB3x0oivZ1fcSXtVdP",
    description: "For consistent content creators",
    popular: true,
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "25 hours of processing",
      "AI picks your 2–3 best clips",
      "Every major platform supported",
      "Blur, crop, or custom background",
      "Download ready to post",
      "Faster processing queue",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    hours: 60,
    monthlyPrice: 66,
    oneTimePrice: 76,
    monthlyPriceId: "price_1UCbBxIB3x0oivZ1cTox2bnr",
    oneTimePriceId: "price_1UCbHxIB3x0oivZ15VHNJkGm",
    description: "For high-volume creators",
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "60 hours of processing",
      "AI picks your 2–3 best clips",
      "Every major platform supported",
      "Blur, crop, or custom background",
      "Download ready to post",
      "Fastest processing queue",
      "Direct support from the team",
    ],
  },
];
