import { loadStripe } from "@stripe/stripe-js";

export const stripePromise = loadStripe(
  import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
);

export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    hours: 10,
    monthlyPrice: 29,
    oneTimePrice: 35,
    monthlyPriceId: "price_1ToKspHTjUJCdbgvSu1udGJC",
    oneTimePriceId: "price_1TuQU2HTjUJCdbgvt51virST",
    description: "Perfect for getting started",
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "10 hours of video",
      "All platforms supported",
      "File upload",
      "Crop, blur & custom styles",
      "Publish to YouTube & Facebook",
      "Download clips",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    hours: 25,
    monthlyPrice: 59,
    oneTimePrice: 69,
    monthlyPriceId: "price_1ToKu7HTjUJCdbgvcLG0Qni0",
    oneTimePriceId: "price_1TuQTQHTjUJCdbgvdlk1AiyS",
    description: "For consistent content creators",
    popular: true,
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "25 hours of video",
      "All platforms supported",
      "File upload",
      "Crop, blur & custom styles",
      "Publish to YouTube & Facebook",
      "Download clips",
      "Priority processing",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    hours: 60,
    monthlyPrice: 99,
    oneTimePrice: 115,
    monthlyPriceId: "price_1ToKuUHTjUJCdbgv7XRLSwIk",
    oneTimePriceId: "price_1TuQScHTjUJCdbgvYhlKeJqN",
    description: "For high-volume creators",
    platforms: [
      "YouTube",
      "Facebook",
      "Instagram",
      "Vimeo",
      "TikTok",
      "Rumble",
      "Loom",
      "Dropbox",
      "Upload",
    ],
    features: [
      "60 hours of video",
      "All platforms supported",
      "File upload",
      "Crop, blur & custom styles",
      "Publish to YouTube & Facebook",
      "Download clips",
      "Priority processing",
      "Dedicated support",
    ],
  },
];
